export const projektleiterData = [
  "Chris Dosch",
  "Andre Wenger",
  "Pascal Nägeli",
  "Markus Vogt",
  "Nick Frosch",
  "Otavio Andrade Souza",
  "Patrick Schneider",
  "Philipp Locher",
  "Ralph Weidmann",
  "Sima Asani",
].map((name, index) => ({
  name,
  email: `projektleiter${index + 1}@qualicasa.ch`,
  aktiv: true,
}));

export const bereichTemplateData = [
  {
    bauteilName: "Rohbau",
    bereiche: [
      {
        name: "Vorbedingungen",
        kapitel: [
          {
            name: "Empfehlungen",
            texte: [
              "Generell müssen Änderungen im Voraus vom TU-Angezeigt und von der Bauherrschaft schriftlich genehmigt werden.",
              "Der Bauherr hat das Recht, einen externen Berater beizuziehen (QualiCasa).\nSämtliche Rückmeldungen, die gefordert werden, sind abzuklären und dem QM zurückzumelden.",
              "Kontrollrecht und Vertretung des Bestellers\nDer Besteller oder ihr Beauftragter sind berechtigt, aber nicht verpflichtet, den Planungs- und Baufortschritt sowie die Bauausführung jederzeit zu kontrollieren oder kontrollieren zu lassen. Der TU ist jederzeit zur Auskunft verpflichtet und hat dem Besteller uneingeschränkt Einblick in die Projektunterlagen zu gewähren.",
              "Der Bauherr hat das Recht, einen externen Berater beizuziehen.",
            ],
          },
          {
            name: "Normen, Empfehlungen",
            texte: [
              "Die Bauausführung erfolgt nach den gültigen SIA-Normen, SIA-Empfehlungen und den Richtlinien der jeweiligen Fachverbände und behördlichen Vorschriften und Empfehlungen.\nSicherheitsvorschriften der SUVA und des BfU sind einzuhalten.\nDie Gliederung dieses Baubeschriebs erfolgt nach den BKP-Positionen.",
              "Angaben der Schallschutzanforderungen gemäss. SIA 181:2020.\nDer Heizwärmebedarf bzw. Energienachweis wird nach SIA 380/1:2016 bestimmt?",
              "Die Bauausführung erfolgt nach den gültigen SIA-Normen, SIA-Empfehlungen und den Richtlinien der jeweiligen Fachverbände und behördlichen Vorschriften und Empfehlungen.\nDie Ausführung erfolgt in allen Teilen in Übereinstimmung mit den geltenden Bauvorschriften und Normen sowie nach den allgemeinen Regeln der Baukunst. Die Gliederung dieses Baubeschriebs erfolgt nach den BKP-Positionen.",
              "Die Gläser entsprechen der SIGAB-Richtline 002.\nDie Gläser werden nach der SIGAB-Richtline 102 gereinigt.\nVorhandene Glaskratzer werden nach der SIGAB Richtline 006 beurteilt.",
            ],
          },
          {
            name: "Mängelrecht",
            texte: [
              "Grundsatz\nDer Unternehmer haftet dafür, dass sein Werk keine Mängel aufweist (SIA 118 Art. 165/166). Er haftet ohne Rücksicht auf die Ursache des Mangels (z.B. unsorgfältige Arbeit, Verwendung untauglichen Materials, eigenmächtiges Abweichen von Plänen und Vorschriften der Bauleitung) und unabhängig vom Verschulden.",
            ],
          },
          {
            name: "Abnahmenkonzept",
            texte: [
              "Allgemein\nDer Start der Garantiefristen erfolgt über das gesamte Werk mit der erfolgreichen Schlussabnahme Werkübergabe, voraussichtlich (Datum)",
              "Allgemein\nIm Grundsatz richtet sich der Abnahme- und Garantieprozess nach den Vorgaben der entsprechenden SIA-Normen. Dies sind im Speziellen die SIA-Normen 118 (2013), 102 (2013), 103 (2013), 105 (2013) und 108 (2013). Ergänzend sind die Präzisierungen in den Planerverträgen sowie den Vorgaben der Bauherrschaft zu beachten.\nIn Abänderung zur SIA 118 wird die Rügefrist auf 5 Jahre verlängert.",
            ],
          },
          {
            name: "Materialwahl",
            texte: [
              "Bauweise und Werkstoffwahl der Leitungen gehen aus der Materialspezifikation hervor. Art, Fabrikat, Materialwahl sowie Verbindungen sind für den Unternehmer bindend. Produkteänderungen können nur toleriert werden, wenn der Bauherr, bzw. sein Vertreter dafür seine Zustimmung gibt.",
            ],
          },
          {
            name: "Schützen von Bauteilen",
            texte: [
              "Leitungen sowie Verbindungen sind während der Lagerung auf der Baustelle und nach der Montage bis zur Abnahme vor Schmutz, korrosiven Einflüssen und Beschädigungen zu schützen.",
            ],
          },
          {
            name: "Bezeichnungen Apparate",
            texte: [
              "Beschriftungen (nach SIA 410)\nAlle Anlageteile wie Kessel, Speicher, Armaturen, Pumpen, Schalt-, Regel-, und Kontrollinstrumente werden mit der Apparatebezeichnung und Anlage-/Apparatenummer gemäss den Schemaunterlagen bezeichnet. Es sind Alu-Schilder mit eingraviertem Text zu verwenden. Die Schilder sind mit Schrauben zu befestigen, oder bei demontierbaren Teilen mit einem Kettchen festzumachen. Die Leitungen werden nach Angaben der Bauleitung mit selbstklebenden Farbpfeilen gekennzeichnet.",
            ],
          },
          {
            name: "Regelung zur Nachjustierung von Fenstern und Türen",
            texte: [
              "Ist aus Sicht QC in den Vorspann zu integrieren:\n\nIm Rahmen der Vertragsgrundlagen wird festgelegt, dass das Nachjustieren von Fenstern und Türen Bestandteil der zweijährigen Garantiezeit ist, sofern diese nicht durch unsachgemässen Gebrauch oder äussere Einflüsse verursacht wurden.\nDie Nachjustierung erfolgt ohne zusätzliche Kosten für den Auftraggeber innerhalb der Garantiefrist.",
            ],
          },
          {
            name: "Betriebsoptimierung",
            texte: [
              "Ist aus Sicht QC in den Vorspann zu integrieren:\n\nIm ersten und zweiten Betriebsjahr wird die Betriebsoptimierung als integraler Bestandteil der Leistung durchgeführt. Dabei soll das Ziel verfolgt werden, dass dadurch keine Komforteinbusse für den Gebäudenutzer entstehen. Es geht hierbei darum die Regeleinstellung der Anlage so zu optimieren, dass die Anlage optimal funktioniert.\nBei der Betriebsoptimierung liegt der Fokus darauf, die bestehenden Anlagen, Systeme und Prozesse effizienter zu gestalten und ihre Leistung zu maximieren.",
              "Ist aus Sicht QC in den Vorspann zu integrieren:\n\nBei komplexen Anlagen resp. Systemen (bspw. Gebäudeautomationssystem) besteht nach der Inbetriebsetzung, Abnahme und Mängelbehebung noch beträchtliches Optimierungspotential. Durch eine fachliche Nachbetreuung seitens der planenden resp. ausführenden Unternehmer soll dieses Optimierungspotential ausgeschöpft werden. Im Rahmen der Betriebsoptimierung ist eine Nachjustierung der Gebäude/Anlagen/Systeme, etc. innerhalb der ersten 2 Betriebsjahre jeweils während der Heiz- und Kühlperiode (Winter– und Sommer) durch die ausführenden Firmen unter der Leitung des relevanten Fachplaners umzusetzen. Dadurch soll unter anderem Folgendes erreicht werden:\n- Optimale Integration von etwaigen Anlagen des Mieterausbaus\n- Minimierung des Energieverbrauchs und der Betriebskosten\n- Optimale Funktionalität und Zuverlässigkeit der Anlagen\n- Schriftlicher Bericht des Fachplaners für die Einhaltung der Projektvorgaben bezüglich Energieverbrauch und Raumkomfort\n\nDie Nachbetreuung resp. Sicherstellung von Betriebsoptimierungen durch zuständige Unternehmer ist in die entsprechenden Submissionen zu integrieren.",
            ],
          },
          {
            name: "Leistungs- und Funktionsgarantie",
            texte: [
              "Ist aus Sicht QC in den Vorspann zu integrieren:\nDer Unternehmer hat zu Beginn der Optimierungsphase, beginnend ein Quartal nach Übergabe des Werkes, den Leistungsnachweis abzuliefern, dass die in den Submissionsunterlagen definierten Werte, Leistungen und Funktionen der Anlagen und Systeme durch die einzelnen Anlagen und Systeme über das erste Betriebsjahr erzielt werden. Dazu sind vom Unternehmer monatliche Rapportings zu erstellen mit einem Analyse- und Massnahmenkatalog zur Erreichung der Soll-Zustände. Die Einzelmassnahmen sind durch den Unternehmer zu koordinieren und zu dokumentieren. Dazu sind die erforderlichen Trend- und Datenaufzeichnungen durch den Gewerksunternehmer vorgängig festzulegen. Der entsprechende Trend und Datenaufzeichnungen erfolgen durch den GA-Unternehmer. Der Leistungsnachweis enthält folgende Leistungen, welche im Angebot einzurechnen sind: \n\n• dauernde Aufzeichnung, Speicherung und Darstellung der Messdaten über mehrere Wochen im Winter, in der Übergangszeit und im Sommer\n\n• dauernde Aufzeichnung, Speicherung und Darstellung des dynamischen Anlagenverhaltens mehrere Wochen im Winter, in der Übergangszeit und im Sommer\n• Stabiles Regelverhalten aller Anlagen\n• Wirkungsgrad der WRG-Systeme der Lüftungs- und Klimaanlagen\n• Raumtemperaturen\n• nicht abschliessend, alles, was zum vollständigen Nachweis eines einwandfreien Betriebes notwendig ist.",
            ],
          },
          {
            name: "Hindernisfreies Bauen",
            texte: [
              "Ist aus Sicht QC in den Vorspann zu integrieren:\n\nEs ist zu prüfen, wie weit die SIA 500 im Projekt integriert wird. Es sollte dem behindertengerechten Bauen Rechnung getragen werden (Momentan bereits Massnahmen auf den Architekturgrundrissen ersichtlich).\nEs ist zu erwähnen, dass bereits Vorbereitungsarbeiten wie Ausholzungen in den Vorwänden, Stellplätze, Wendeplatz vorgängig mit einbezogen werden müssen.",
            ],
          },
        ],
      },
    ],
  },
];

export const kontaktData = [
  {
    name: "Qualicasa Support",
    email: "support@qualicasa.ch",
    aktiv: true,
  },
  {
    name: "Eva Muster",
    email: "eva.muster@testkunden.ch",
    aktiv: true,
  },
  {
    name: "Peter Beispiel",
    email: "peter.beispiel@testkunden.ch",
    aktiv: true,
  },
  {
    name: "Claudia Meier",
    email: "claudia.meier@testkunden.ch",
    aktiv: true,
  },
  {
    name: "Martin Keller",
    email: "martin.keller@testkunden.ch",
    aktiv: true,
  },
];

export const dummyKundenData = [
  {
    name: "Testkunde Alpha AG",
    adresse: "Bahnhofstrasse 12",
    plz: "8001",
    ort: "Zürich",
    kontaktEmail: "eva.muster@testkunden.ch",
    projektleiterName: "Chris Dosch",
    objekte: [
      {
        bezeichnung: "Wohnüberbauung Alpha",
        adresse: "Im Park 4",
        plz: "8001",
        ort: "Zürich",
        objekttypBezeichnung: "Mehrfamilienhaus",
      },
    ],
  },
  {
    name: "Testkunde Beta GmbH",
    adresse: "Seestrasse 45",
    plz: "6004",
    ort: "Luzern",
    kontaktEmail: "peter.beispiel@testkunden.ch",
    projektleiterName: "Andre Wenger",
    objekte: [
      {
        bezeichnung: "Gewerbepark Beta",
        adresse: "Industriestrasse 8",
        plz: "6005",
        ort: "Luzern",
        objekttypBezeichnung: "Gewerbebau",
      },
      {
        bezeichnung: "Parkhaus Beta",
        adresse: "Pilatusstrasse 20",
        plz: "6003",
        ort: "Luzern",
        objekttypBezeichnung: "Parkhaus",
      },
    ],
  },
  {
    name: "Testkunde Gamma AG",
    adresse: "Poststrasse 7",
    plz: "9000",
    ort: "St. Gallen",
    kontaktEmail: "claudia.meier@testkunden.ch",
    projektleiterName: "Pascal Nägeli",
    objekte: [
      {
        bezeichnung: "Schulcampus Gamma",
        adresse: "Schulstrasse 14",
        plz: "9010",
        ort: "St. Gallen",
        objekttypBezeichnung: "Schulgebäude",
      },
    ],
  },
  {
    name: "Testkunde Delta AG",
    adresse: "Marktplatz 3",
    plz: "3001",
    ort: "Bern",
    kontaktEmail: "martin.keller@testkunden.ch",
    projektleiterName: "Nick Frosch",
    objekte: [
      {
        bezeichnung: "City Hotel Delta",
        adresse: "Bundesgasse 17",
        plz: "3011",
        ort: "Bern",
        objekttypBezeichnung: "Hotel/bewirtung",
      },
      {
        bezeichnung: "Verwaltungszentrum Delta",
        adresse: "Laubeggstrasse 6",
        plz: "3006",
        ort: "Bern",
        objekttypBezeichnung: "Verwaltungsgebäude",
      },
    ],
  },
];

export const objekttypData = [
  "Hallenbad",
  "MFH Einfach",
  "EFH",
  "Bürobau oder Verwaltungsbau",
  "Warenhaus",
  "Schulgebäude",
  "Turnhalle",
  "Parkhaus",
  "Gewerbebau",
  "Tiefgarage",
  "MFH Gemischt",
  "MFH Einfach",
  "MFH Gemischt (Wohnen/Gewerbe)",
  "Geschäftshaus",
  "Garagenbox",
  "Sakralbau",
  "Lagerschuppen",
  "Schulhaus",
  "Labor- und Forschungsgebäude",
  "Werkhof",
  "Gewächshaus",
  "Polizei- und Feuerwehrgebäude",
  "Kulturgebäude",
  "Restaurationsbetrieb",
  "Bankfiliale",
  "Bankgebäude",
  "Mieterausbau",
  "Verwaltungsgebäude",
  "Viersternehotel",
  "Mehrfamilienhaus",
  "Eigentumswohnung",
  "Einfamilienhaus",
  "Wohn- und Geschäftshaus",
  "Einzelhandelsfläche",
  "Lager",
  "Einkaufszentrum",
  "Fachmarkt",
  "Industriebau",
  "Logistikbau",
  "Speziallager",
  "Hotel/bewirtung",
  "Gesundheitsbau",
  "Bildungsbau",
  "Projekt",
  "Grundstück",
  "Baurecht",
].map((bezeichnung) => ({ bezeichnung, aktiv: true }));

export const baurundgangTypData = [
  { nummer: 1, name: "Phase 1 – Vorbereitungsrundgang", reihenfolge: 1, aktiv: true },
  { nummer: 2, name: "Phase 2 – Rohbau", reihenfolge: 2, aktiv: true },
  { nummer: 3, name: "Phase 3 – Ausbau", reihenfolge: 3, aktiv: true },
];

export const bauteilTemplateData = [
  "Rohbau",
  "Steildach",
  "Flachdach",
  "Fassaden",
  "Fenster",
  "Läden/Sonnenschutz",
  "Elektro",
  "Wärmeerzeugung",
  "Wärmeverteilung",
  "Lüftungsanlagen",
  "Übrige Gebäudetechnik",
  "Sanitär",
  "Innenausbau Bad/WC",
  "Innenausbau Küche",
  "Übriger Innenausbau",
  "Lifte/Hebebühnen",
  "Türen/Tore",
  "Tiefbau/Umgebung",
].map((name, index) => ({
  name,
  reihenfolge: index + 1,
  aktiv: true,
}));

export const materialisierungTemplateData = [
  {
    bauteilName: "Elektro",
    materialisierungen: ["Standard", "Unterdurchschnittlich", "Überdurchschnittlich", "Gehoben"],
  },
  {
    bauteilName: "Fassaden",
    materialisierungen: [
      "Standard",
      "Mauerwerk verputzt",
      "Sichtmauerwerk",
      "Sichtbeton",
      "Kompaktfassade verputzt",
      "Holzschindeln",
      "Holz",
      "Fachwerk",
      "Faserzement",
      "Metall",
      "Glas",
      "Naturstein",
      "Kunststein",
      "Keramik",
      "Module mit integriereter Photovoltaik",
      "Metallgewebe",
      "Historisch",
      "funktionsfähig",
      "beschädigt",
      "Granit",
      "Holzrost",
      "Verbundsteine",
      "Pflasterstein",
      "Fallschutzmatten",
      "Mergel",
      "Bekiest",
      "Beton",
      "Andere",
    ],
  },
  {
    bauteilName: "Fenster",
    materialisierungen: [
      "Standard",
      "Holz",
      "Holz-Metall",
      "Metall",
      "Kunststoff",
      "Kunststoff-Metall",
      "Historisch",
      "klein",
      "normal",
      "hoch",
      "Schallschutz",
      "Einbruchschutz",
    ],
  },
  {
    bauteilName: "Flachdach",
    materialisierungen: [
      "Standard",
      "Kunststoff",
      "Kunststoff mit Kies/Schotter",
      "Kunststoff intensiv begrünt",
      "Kunststoff extensiv begrünt",
      "Kunststoff begehbar",
      "Bitumen",
      "Bitumen mit Kies/Schotter",
      "Bitumen intensiv begrünt",
      "Bitumen extensiv begrünt",
      "Bitumen begehbar",
      "Kautschuk",
      "Kautschuk mit Kies/Schotter",
      "Kautschuk intensiv begrünt",
      "Kautschuk extensiv begrünt",
      "Kautschuk begehbar",
      "Warmdach",
      "Kaltdach",
      "Umkehrdach",
      "Stahlbeton",
      "Asphalt",
      "Stahlbeton mit Beschichtung",
      "einschalig",
      "zweischalig",
      "hinterlüftet",
      "vorgehängt",
    ],
  },
  {
    bauteilName: "Innenausbau Bad/WC",
    materialisierungen: ["Bad/DU/WC Gästezimmer"],
  },
  {
    bauteilName: "Innenausbau Küche",
    materialisierungen: ["Standard", "Unterdurchschnittlich", "Überdurchschnittlich", "Gehoben"],
  },
  {
    bauteilName: "Läden/Sonnenschutz",
    materialisierungen: [
      "Standard",
      "Rollläden Holz manuell",
      "Rollläden Holz elektrisch",
      "Rollläden Kunststoff manuell",
      "Rollläden Kunststoff elektrisch",
      "Rollläden Metall manuell",
      "Rollläden Metall elektrisch",
      "Lamellenstoren manuell",
      "Lamellenstoren elektrisch",
      "Fensterläden Holz",
      "Fensterläden Metall",
      "Markisen/Stoffstoren manuell",
      "Markisen/Stoffstoren elektrisch",
      "Sonnenschutz",
      "Blendschutz",
    ],
  },
  {
    bauteilName: "Lifte/Hebebühnen",
    materialisierungen: [
      "Standard",
      "Personenlift",
      "Warenlift",
      "Hebebühne",
      "Autolift",
      "Krananlage/Brückenkran",
      "Rolltreppen/Förderbänder",
      "elektrisch",
      "hydraulisch",
    ],
  },
  {
    bauteilName: "Lüftungsanlagen",
    materialisierungen: [
      "Standard",
      "Gewerbliche Kälte",
      "Lüftung",
      "Lüftung/Kühlung",
      "Lüftung/Kühlung/Befeuchtung",
      "Kontrollierte Wohnungslüftung",
      "Splittgeräte (Klimatisierung)",
      "Kühldecke (Kühlung)",
      "Splitgerät",
      "zentral",
    ],
  },
  {
    bauteilName: "Rohbau",
    materialisierungen: [
      "Standard",
      "Massivbau",
      "Skelettbau",
      "Mischbau Massiv-/Skelettbau",
      "Mischbau Leicht-/Fertigbau",
      "Leichtbau",
      "Fachwerk",
      "Plattenbau",
      "Historisch",
      "schlecht",
      "mittel",
      "gut",
      "neu",
      "freistehend",
      "einseitig angebaut",
      "Reihenhaus",
      "Eckhaus",
      "schwer",
      "leicht",
      "sehr leicht",
    ],
  },
  {
    bauteilName: "Sanitär",
    materialisierungen: [
      "Standard",
      "Unterdurchschnittlich",
      "Überdurchschnittlich",
      "Gehoben",
      "einzel",
      "doppel",
      "einzel und doppel",
      "Dusche-WC",
      "Gusseisen, Originalzustand",
      "Gusseisen, saniert (Inliner)",
      "PVC (braun), Originalzustand",
      "PVC (braun), saniert (Inliner)",
      "PE (schwarz), Originalzustand",
      "PE (schwarz), saniert (Inliner)",
      "Stahl verzinkt (silber)",
      "Kupferrohr (rot)",
      "Kunststoff",
      "Chromstahl",
      "Emailliert",
      "Edelstahl",
      "zentral",
      "WP-Boiler",
      "dezentral (Elektro)",
      "dezentral (Gas)",
    ],
  },
  {
    bauteilName: "Steildach",
    materialisierungen: [
      "Standard",
      "Ziegel",
      "Betondachstein",
      "Faserzement",
      "Metall",
      "Glas",
      "Naturstein",
      "Giebeldach",
      "Satteldach",
      "Pultdach",
      "Walmdach",
      "Mansarddach",
      "Kupfer",
      "Edelstahl",
      "Uginox",
      "Kunststoff",
      "Andere",
    ],
  },
  {
    bauteilName: "Tiefbau/Umgebung",
    materialisierungen: ["Standard", "Unterdurchschnittlich", "Überdurchschnittlich", "Gehoben", "Tiefgarage", "Garagenbox"],
  },
  {
    bauteilName: "Türen/Tore",
    materialisierungen: [
      "Standard",
      "Holz",
      "Holz-Metall",
      "Metall",
      "Kunststoff",
      "Kunststoff-Metall",
      "Historisch",
      "elektrisch",
      "manuell",
      "Massivholz",
      "MDF",
      "Glas",
      "Rolltor",
      "Sektionaltor",
      "Kipptor",
      "Gittertor",
      "Schiebetor",
      "Falttor",
      "Drehtür",
      "Schiebetür",
      "Schwenktür",
      "klein",
      "normal",
      "hoch",
      "Schallschutz",
      "Einbruchschutz",
    ],
  },
  {
    bauteilName: "Übrige Gebäudetechnik",
    materialisierungen: ["Standard", "Unterdurchschnittlich", "Überdurchschnittlich", "Gehoben"],
  },
  {
    bauteilName: "Übriger Innenausbau",
    materialisierungen: [
      "Standard",
      "Massivbau",
      "Leichtbau",
      "Historisch",
      "massiv",
      "leicht",
      "Büro",
      "Einliegerwohnung",
      "Verkauf",
      "Bankausbau",
      "übr. Ausbau",
      "Restaurant",
      "Fitness",
      "Oberflächen Gästezimmer",
      "Viersternhotel",
      "Unterdurchschnittlich",
      "Überdurchschnittlich",
      "Gehoben",
      "Parkett",
      "Laminat",
      "Kunststoff",
      "Naturstein",
      "Keramik",
      "Textiler Bodenbelag",
      "Unterlagsboden",
      "Rohbau",
      "Dielen",
      "Kunstharz",
      "PVC",
      "Linoleum",
      "Andere",
      "Beton",
      "Holz",
      "Anstrich",
      "Verputz Abrieb",
      "Weissputz",
      "Stuckatur",
      "Rohbaudecke",
      "Abgehänkte Decke",
      "Gespachtelte Decke",
      "Tapete",
      "Abrieb",
      "Glas",
    ],
  },
  {
    bauteilName: "Wärmeerzeugung",
    materialisierungen: [
      "Standard",
      "Gasheizung",
      "Ölheizung",
      "Öl-/Gas-Kombi-Heizung",
      "Fernwärme",
      "Blockheizkraftwerk",
      "Holzpellets",
      "Holzschnitzel",
      "Stückholz",
      "Elektro/Elektrospeicher",
      "Wärmepumpe",
      "Wärmepumpe Erdsonde",
      "Wärmepumpe Erdregister",
      "Wärmepumpe Luft/Wasser",
      "Edelstahl",
      "Kunststoff",
      "Keramik/Schamotte",
      "Aussen",
      "Innen",
      "kondensierend",
      "nicht kondensierend",
      "Heizung",
      "Warmwasser",
      "H + WW ganzjährig",
      "H + WW nur Heizperiode",
      "Gas",
      "Öl",
      "Wärmelieferant",
      "Gebäudeeigentümer",
      "knapp",
      "grosszügig",
      "Seewasser",
      "Grundwasser",
      "Luft - Luft",
    ],
  },
  {
    bauteilName: "Wärmeverteilung",
    materialisierungen: [
      "Standard",
      "Heizkörper",
      "Bodenheizung",
      "Deckenheizung",
      "Warmluft",
      "Wandheizung",
      "Ofen zentral",
      "Thermoaktive Bauteilsysteme (TABS)",
      "Edelstahl",
      "Stahl",
      "Keramik/Schamotte",
    ],
  },
];

export const bauteilRisikoData = [
  { name: "Feuchtigkeit", aktiv: true },
  { name: "Rissbildung", aktiv: true },
  { name: "Schimmel", aktiv: true },
  { name: "Korrosion", aktiv: true },
];

export const rueckmeldungstypData = [
  { typCode: "OK", name: "In Ordnung" },
  { typCode: "MANGEL", name: "Mangel" },
  { typCode: "HINWEIS", name: "Hinweis" },
  { typCode: "INFO", name: "Information" },
];
